Last login: Sun Aug 21 18:04:35 on ttys002
You have new mail.
➜  ~ cd Desktop/Progetto_PWM
➜  Progetto_PWM git:(master) ✗ nodemon
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
Server running on 3000
Connected to MongoDB!
(node:18411) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
QUAQUA
[
  {
    sections: [ [Object], [Object] ],
    compilations: [],
    tips_and_ratings_enabled: true,
    approved_at: 1660314798,
    renditions: [],
    original_video_url: null,
    user_ratings: { score: 1, count_negative: 0, count_positive: 3 },
    servings_noun_singular: 'serving',
    tags: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    show: { name: 'Tasty', id: 17 },
    updated_at: 1660314798,
    yields: 'Servings: 4',
    brand: null,
    show_id: 17,
    nutrition: {},
    credits: [ [Object] ],
    slug: 'shrimp-summer-salad-with-creamy-cilantro-dressing',
    facebook_posts: [],
    id: 8412,
    num_servings: 4,
    thumbnail_url: 'https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/dbccd3ca691b467185d910918146407c.jpeg',
    keywords: '',
    total_time_minutes: 20,
    is_one_top: false,
    cook_time_minutes: 0,
    description: 'Summer is coming to an end, so we have to take advantage of all the bountiful seasonal produce while we still can. Enjoy this refreshing and delicious salad with all the flavors summer has to offer, like cucumbers, mini heirloom tomatoes, baby corn, mango, and avocado.',
    name: 'Shrimp Summer Salad With Creamy Cilantro Dressing',
    created_at: 1660250170,
    is_shoppable: true,
    video_ad_content: null,
    seo_title: 'Shrimp Salad with CIlantro Dressing',
    promotion: 'full',
    video_id: null,
    brand_id: null,
    country: 'US',
    instructions: [ [Object], [Object], [Object], [Object], [Object] ],
    language: 'eng',
    prep_time_minutes: 20,
    buzz_id: null,
    aspect_ratio: '16:9',
    servings_noun_plural: 'servings',
    nutrition_visibility: 'auto',
    topics: [ [Object], [Object], [Object], [Object], [Object] ],
    total_time_tier: { tier: 'under_30_minutes', display_tier: 'Under 30 minutes' },
    beauty_url: null,
    inspired_by_url: null,
    thumbnail_alt_text: '',
    video_url: null,
    canonical_id: 'recipe:8412',
    draft_status: 'published'
  },
  {
    servings_noun_singular: 'serving',
    name: 'Grilled Cauliflower Tacos',
    draft_status: 'published',
    servings_noun_plural: 'servings',
    thumbnail_alt_text: '',
    video_url: null,
    video_id: null,
    nutrition_visibility: 'auto',
    instructions: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    brand_id: null,
    compilations: [],
    inspired_by_url: null,
    beauty_url: null,
    id: 8374,
    nutrition: {
      fat: 24,
      calories: 400,
      sugar: 8,
      carbohydrates: 41,
      fiber: 26,
      updated_at: '2022-07-30T08:01:26+02:00',
      protein: 9
    },
    created_at: 1658270087,
    description: 'These cauliflower tacos are spiced to perfection and oh so satisfying. Cauliflower is marinated in a zesty, savory blend of lime juice, brown sugar, and tons of spices, then grilled to charred perfection. To build the tacos, layer the cauliflower on warm tortillas with plenty of the creamy, smoky poblano-pepita sauce, cabbage, cilantro, and crema.',
    yields: 'Servings: 6-8',
    original_video_url: null,
    promotion: 'full',
    keywords: '',
    user_ratings: { count_positive: 3, score: 0.6, count_negative: 2 },
    aspect_ratio: '16:9',
    credits: [ [Object] ],
    tags: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    is_one_top: false,
    topics: [ [Object], [Object], [Object], [Object], [Object] ],
    total_time_tier: { tier: 'under_2.5_hours', display_tier: 'Under 2.5 hours' },
    language: 'eng',
    brand: null,
    slug: 'grilled-cauliflower-tacos',
    show_id: 17,
    show: { name: 'Tasty', id: 17 },
    updated_at: 1659122467,
    approved_at: 1659122466,
    video_ad_content: null,
    country: 'US',
    prep_time_minutes: 20,
    buzz_id: null,
    tips_and_ratings_enabled: true,
    seo_title: '',
    cook_time_minutes: 85,
    facebook_posts: [],
    sections: [ [Object], [Object], [Object] ],
    renditions: [],
    is_shoppable: true,
    num_servings: 6,
    thumbnail_url: 'https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/63a32d85f1da4960a438d8e456f579ee.jpeg',
    total_time_minutes: 135,
    canonical_id: 'recipe:8374'
  },
  {
    sections: [ [Object], [Object], [Object], [Object] ],
    inspired_by_url: null,
    thumbnail_url: 'https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/6fe93160ca4d47528f4510bd4f8081e4.jpeg',
    video_url: null,
    instructions: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    language: 'eng',
    id: 8394,
    slug: 'yuzu-ponzu-salmon-with-crispy-rice',
    is_one_top: false,
    cook_time_minutes: 20,
    promotion: 'full',
    nutrition_visibility: 'auto',
    credits: [ [Object] ],
    video_ad_content: null,
    seo_title: '',
    name: 'Yuzu Ponzu Salmon With Crispy Rice',
    show: { name: 'Tasty', id: 17 },
    draft_status: 'published',
    thumbnail_alt_text: '',
    country: 'US',
    user_ratings: { count_positive: 1, score: 1, count_negative: 0 },
    show_id: 17,
    brand_id: null,
    beauty_url: null,
    total_time_tier: { display_tier: 'Under 2 hours', tier: 'under_2_hours' },
    original_video_url: null,
    description: 'Yuzu kosho and salmon make an unbeatable pair in this yuzu ponzu salmon-topped crispy sushi rice. These fun bites make the perfect appetizer!',
    is_shoppable: true,
    topics: [ [Object], [Object], [Object], [Object] ],
    facebook_posts: [],
    brand: null,
    nutrition: {
      fat: 22,
      calories: 224,
      sugar: 1,
      carbohydrates: 1,
      fiber: 4,
      updated_at: '2022-07-30T08:01:27+02:00',
      protein: 3
    },
    num_servings: 12,
    video_id: null,
    keywords: '',
    prep_time_minutes: 15,
    tags: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    yields: 'Makes 12 pieces',
    total_time_minutes: 95,
    renditions: [],
    servings_noun_singular: 'piece',
    compilations: [],
    buzz_id: null,
    tips_and_ratings_enabled: true,
    servings_noun_plural: 'pieces',
    canonical_id: 'recipe:8394',
    aspect_ratio: '16:9',
    created_at: 1659032045,
    updated_at: 1659042860,
    approved_at: 1659042860
  },
  {
    thumbnail_alt_text: '',
    is_shoppable: true,
    cook_time_minutes: 65,
    keywords: '',
    tags: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    name: 'Crispy Smashed Potatoes With Ginger Scallion Sauce',
    show: { name: 'Tasty', id: 17 },
    original_video_url: null,
    promotion: 'full',
    user_ratings: { count_positive: 18, score: 0.857143, count_negative: 3 },
    slug: 'crispy-smashed-potatoes-with-ginger-scallion-sauce',
    sections: [ [Object], [Object] ],
    servings_noun_plural: 'servings',
    total_time_minutes: 85,
    video_url: null,
    credits: [ [Object] ],
    video_ad_content: null,
    servings_noun_singular: 'serving',
    compilations: [],
    created_at: 1658350054,
    draft_status: 'published',
    seo_title: '',
    id: 8381,
    tips_and_ratings_enabled: true,
    beauty_url: null,
    total_time_tier: { tier: 'under_1.5_hours', display_tier: 'Under 1.5 hours' },
    inspired_by_url: null,
    language: 'eng',
    brand: null,
    show_id: 17,
    prep_time_minutes: 20,
    canonical_id: 'recipe:8381',
    brand_id: null,
    nutrition: {
      protein: 1,
      fat: 26,
      calories: 300,
      sugar: 0,
      carbohydrates: 15,
      fiber: 30,
      updated_at: '2022-07-23T08:01:30+02:00'
    },
    buzz_id: null,
    aspect_ratio: '16:9',
    is_one_top: false,
    renditions: [],
    topics: [ [Object], [Object] ],
    yields: 'Servings: 6',
    nutrition_visibility: 'auto',
    num_servings: 6,
    description: 'These crispy smashed potatoes are a notch above your typical spuds. They’re crunchy on the outside, creamy on the inside, and topped with a savory ginger scallion sauce. Serve as a side dish or appetizer.',
    updated_at: 1658536109,
    video_id: null,
    approved_at: 1658536109,
    country: 'US',
    instructions: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    facebook_posts: [],
    thumbnail_url: 'https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/73c00e13e0d040eb827cc080c694a25a.jpeg'
  },
  {
    nutrition_visibility: 'auto',
    instructions: [ [Object], [Object], [Object] ],
    keywords: '',
    brand: null,
    servings_noun_plural: 'servings',
    yields: 'Servings: 8',
    user_ratings: { count_positive: 50, score: 0.724638, count_negative: 19 },
    show: { name: 'Tasty', id: 17 },
    total_time_tier: { tier: 'under_15_minutes', display_tier: 'Under 15 minutes' },
    video_ad_content: null,
    num_servings: 8,
    country: 'US',
    facebook_posts: [],
    slug: 'cowboy-caviar',
    brand_id: null,
    tags: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    nutrition: {
      sugar: 6,
      carbohydrates: 34,
      fiber: 9,
      updated_at: '2022-07-15T08:01:42+02:00',
      protein: 9,
      fat: 22,
      calories: 254
    },
    compilations: [],
    credits: [ [Object] ],
    beauty_url: null,
    promotion: 'full',
    language: 'eng',
    thumbnail_url: 'https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/20be33e21eb147be91bf2a043639b91e.jpeg',
    is_shoppable: true,
    cook_time_minutes: 0,
    video_id: null,
    inspired_by_url: null,
    total_time_minutes: 15,
    updated_at: 1657812314,
    original_video_url: null,
    prep_time_minutes: 10,
    buzz_id: null,
    thumbnail_alt_text: '',
    approved_at: 1657812313,
    is_one_top: false,
    topics: [ [Object], [Object], [Object] ],
    seo_title: 'Cowboy Caviar Recipe',
    servings_noun_singular: 'serving',
    name: 'Cowboy Caviar',
    tips_and_ratings_enabled: true,
    aspect_ratio: '16:9',
    description: 'The cowboy caviar recipe has been one of the most searched and trending recipes of summer 2022. It involves dicing and chopping a lot of vegetables (a definite arm workout, but worth it!), all brought together with a tangy hot honey and lime vinaigrette.',
    video_url: null,
    canonical_id: 'recipe:8358',
    id: 8358,
    show_id: 17,
    sections: [ [Object] ],
    created_at: 1657727827,
    draft_status: 'published',
    renditions: []
  }
]
^C%
➜  Progetto_PWM git:(master) ✗